### ISSUE TITLE
Duck type messages break sometimes.

### ISSUE THREAD

**Issue by jeffmcmahan** [jeffmcmahan/TYPEOF#8]
```js 
 TYPEOF
    (...arguments)
    ({ settings:Object })
```

In one case, the above produced the following when `undefined` was passed:

```
TypeError: Cannot read property 'settings' of undefined
    at .../node_modules/type.of/build/types-match.js:20:82
    at Array.every (native)
    at typesMatch (.../node_modules/type.of/build/types-match.js:20:25)
    at .../node_modules/type.of/build/index.js:62:12
    at Object.exports.writeJson (.../node_modules/standardcms/admin/admin-utils.js:22:5)
    at Promise (.../node_modules/standardcms/admin/index.js:116:23)
    at Object.save (.../node_modules/standardcms/admin/index.js:107:10)
    at handle (.../node_modules/standardcms/admin/index.js:183:27)
    at authenticate.then._ (.../node_modules/standardcms/admin/index.js:208:15)
```

**Comment by jeffmcmahan** [comment]
Fixed in 2b62906.
